export class Pedido {
    constructor(
        public _id                          : string,
        public Number                       : number,
        public Client                       : string,
        public OrderDate                    : string,
        public OrderTime                    : string,
        public DeliveryTime                 : string,
        public DeliveryTimeReplace          : string,
        public GPS                          : string,
        public City                         : string,
        public Address                      : string,
        public AddedBy                      : string,
        public Bodega                       : string,
        public State                        : string,
        public Total                        : number,
        public SubTotal                     : number,
        public TotalDiscount                : number,
        public TotalProdSell                : number,
        public TotalProdFree                : number,
        public SendCost                     : number,
        public Comments                     : string,
        public FindedBy                     : string,
        public ContactedBy                  : string,
        public Deliverer                    : string,
        public DeliveredBy                  : string,
        public Image                        : string,
        public Active                       : boolean,
    ) {}
}
